### ISSUE TITLE
blog.articles variable empty for feed.xml.builder

### ISSUE THREAD

**Issue by jussirasanen** [middleman/middleman-blog#152]
"blog.articles" array seems to be null for the xml builder, yet I'm able to loop "blog.articles" in layout and template .erb files.

My feed.xml.builder file

```
xml.instruct!
xml.feed "xmlns" => "http://www.w3.org/2005/Atom" do
  site_url = "http://blog.url.com/"
  xml.title "Blog Name"
  xml.subtitle "Blog subtitle"
  xml.id URI.join(site_url, blog.options.prefix.to_s)
  xml.link "href" => URI.join(site_url, blog.options.prefix.to_s)
  xml.link "href" => URI.join(site_url, current_page.path), "rel" => "self"
  xml.updated blog.articles.first.date.to_time.iso8601
  xml.author { xml.name "Blog Author" }

  blog.articles[0..5].each do |article|
    xml.entry do
      xml.title article.title
      xml.link "rel" => "alternate", "href" => URI.join(site_url, article.url)
      xml.id URI.join(site_url, article.url)
      xml.published article.date.to_time.iso8601
      xml.updated File.mtime(article.source_file).iso8601
      xml.author { xml.name "Article Author" }
      # xml.summary article.summary, "type" => "html"
      xml.content article.body, "type" => "html"
    end
  end
end
```

config.rb

```
###
# Blog settings
###

activate :blog do |blog|
  blog.default_extension = ".markdown"
  blog.taglink = "categories/:tag.html"
  blog.permalink = "/articles/:title.html"
  blog.layout = "layout"
  blog.tag_template = "tag.html"
  blog.sources = "articles/:title.html"
end

page "articles/*", :layout => :article_layout
page "/feed.xml", :layout => false
page "/sitemap.xml", :layout => false
helpers do
  def author(who)
    who.downcase!
    data.authors.each do |user|
      if user["key"] == who
        return user
      end
    end
    return nil
  end
end

set :markdown_engine, :redcarpet
set :markdown, :fenced_code_blocks => true, :smartypants => true
set :css_dir, 'stylesheets'
set :js_dir, 'javascripts'
set :images_dir, 'images'

configure :build do
end
```

The build output is following

```
== Activating: sprockets
== File Change: data/sitemap.yml
== File Change: data/authors.json
== Reading:  Local config

== Activating: blog
== Activating: deploy
Loaded extensions:
== Extension: sprockets
== Extension: blog
== Extension: deploy
== Extension: frontmatter
== File Change: data/sitemap.yml
== File Change: data/authors.json
== File Change: config.rb
== File Change: source/404.html
== File Change: source/css/.sass-cache/9bfdc06cacbb6309466a045e4c2fd78b0c5fb722/_main.scssc
== File Change: source/css/_main.scss
== File Change: source/css/pure-min.css
== File Change: source/css/main.css
== File Change: source/js/plugins.js
== File Change: source/js/vendor/jquery-1.8.0.min.js
== File Change: source/js/vendor/modernizr-2.6.1.min.js
== File Change: source/js/main.js
== File Change: source/tag.html.erb
== File Change: source/feed.xml.builder
== File Change: source/favicon.ico
== File Change: source/.htaccess
== File Change: source/sitemap.xml.builder
== File Change: source/crossdomain.xml
== File Change: source/img/.gitignore
== File Change: source/robots.txt
== File Change: source/images/favicon.ico
== File Change: source/index.html.erb
== File Change: source/humans.txt
== File Change: source/layouts/article_layout.erb
== File Change: source/layouts/_article_meta.erb
== File Change: source/layouts/layout.erb
== File Change: source/layout.erb
== File Change: source/articles/backup-mx-and-postfix.html.markdown
== Rebuilding resource list
== Prerendering CSS
== Request: /css/pure-min.css
== Finishing Request: css/pure-min.css (0.0s)
== Request: /css/main.css
== Finishing Request: css/main.css (0.0s)
== Checking for Compass sprites
== Building files
   identical  build/favicon.ico
   identical  build/images/favicon.ico
== Request: /js/vendor/jquery-1.8.0.min.js
== Finishing Request: js/vendor/jquery-1.8.0.min.js (0.0s)
   identical  build/js/vendor/jquery-1.8.0.min.js
== Request: /js/plugins.js
== Finishing Request: js/plugins.js (0.0s)
   identical  build/js/plugins.js
== Request: /js/main.js
== Finishing Request: js/main.js (0.0s)
   identical  build/js/main.js
== Request: /js/vendor/modernizr-2.6.1.min.js
== Finishing Request: js/vendor/modernizr-2.6.1.min.js (0.0s)
   identical  build/js/vendor/modernizr-2.6.1.min.js
== Request: /css/pure-min.css
== Finishing Request: css/pure-min.css (0.0s)
   identical  build/css/pure-min.css
== Request: /css/main.css
== Finishing Request: css/main.css (0.0s)
   identical  build/css/main.css
== Request: /404.html
== Finishing Request: 404.html (0.0s)
   identical  build/404.html
== Request: /.htaccess
== Finishing Request: .htaccess (0.0s)
   identical  build/.htaccess
== Request: /sitemap.xml
== Finishing Request: sitemap.xml (0.0s)
   identical  build/sitemap.xml
== Request: /crossdomain.xml
== Finishing Request: crossdomain.xml (0.0s)
   identical  build/crossdomain.xml
== Request: /robots.txt
== Finishing Request: robots.txt (0.0s)
   identical  build/robots.txt
== Request: /feed.xml
       error  build/feed.xml
undefined method `date' for nil:NilClass
/home/jrasanen/development/internal/projects/blog/source/feed.xml.builder:9:in `block (2 levels) in singletonclass'
/var/lib/gems/1.9.1/gems/builder-3.0.4/lib/builder/xmlbase.rb:170:in `call'
/var/lib/gems/1.9.1/gems/builder-3.0.4/lib/builder/xmlbase.rb:170:in `_nested_structures'
/var/lib/gems/1.9.1/gems/builder-3.0.4/lib/builder/xmlbase.rb:63:in `tag!'
/var/lib/gems/1.9.1/gems/builder-3.0.4/lib/builder/xmlbase.rb:88:in `method_missing'
/home/jrasanen/development/internal/projects/blog/source/feed.xml.builder:2:in `block in singletonclass'
/home/jrasanen/development/internal/projects/blog/source/feed.xml.builder:65534:in `instance_eval'
/home/jrasanen/development/internal/projects/blog/source/feed.xml.builder:65534:in `singletonclass'
/home/jrasanen/development/internal/projects/blog/source/feed.xml.builder:65532:in `__tilt_13567980'
/var/lib/gems/1.9.1/gems/tilt-1.3.7/lib/tilt/template.rb:144:in `call'
/var/lib/gems/1.9.1/gems/tilt-1.3.7/lib/tilt/template.rb:144:in `evaluate'
/var/lib/gems/1.9.1/gems/tilt-1.3.7/lib/tilt/builder.rb:20:in `evaluate'
/var/lib/gems/1.9.1/gems/tilt-1.3.7/lib/tilt/template.rb:77:in `render'
/var/lib/gems/1.9.1/gems/middleman-core-3.1.4/lib/middleman-core/core_extensions/rendering.rb:273:in `render_individual_file'
/var/lib/gems/1.9.1/gems/middleman-core-3.1.4/lib/middleman-core/core_extensions/rendering.rb:150:in `render_template'
/var/lib/gems/1.9.1/gems/middleman-core-3.1.4/lib/middleman-core/sitemap/resource.rb:150:in `block in render'
/var/lib/gems/1.9.1/gems/activesupport-3.2.14/lib/active_support/notifications.rb:125:in `instrument'
/var/lib/gems/1.9.1/gems/middleman-core-3.1.4/lib/middleman-core/util.rb:60:in `instrument'
/var/lib/gems/1.9.1/gems/middleman-core-3.1.4/lib/middleman-core/application.rb:196:in `instrument'
/var/lib/gems/1.9.1/gems/middleman-core-3.1.4/lib/middleman-core/sitemap/resource.rb:16:in `instrument'
/var/lib/gems/1.9.1/gems/middleman-core-3.1.4/lib/middleman-core/sitemap/resource.rb:121:in `render'
/var/lib/gems/1.9.1/gems/middleman-core-3.1.4/lib/middleman-core/core_extensions/request.rb:252:in `process_request'
/var/lib/gems/1.9.1/gems/middleman-core-3.1.4/lib/middleman-core/core_extensions/request.rb:202:in `block in call!'
/var/lib/gems/1.9.1/gems/middleman-core-3.1.4/lib/middleman-core/core_extensions/request.rb:201:in `catch'
/var/lib/gems/1.9.1/gems/middleman-core-3.1.4/lib/middleman-core/core_extensions/request.rb:201:in `call!'
/var/lib/gems/1.9.1/gems/middleman-core-3.1.4/lib/middleman-core/core_extensions/request.rb:187:in `call'
/var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:138:in `call'
/var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/urlmap.rb:65:in `block in call'
/var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `each'
/var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `call'
/var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/lint.rb:49:in `_call'
/var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/lint.rb:37:in `call'
/var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:138:in `call'
/var/lib/gems/1.9.1/gems/rack-test-0.6.2/lib/rack/mock_session.rb:30:in `request'
/var/lib/gems/1.9.1/gems/rack-test-0.6.2/lib/rack/test.rb:230:in `process_request'
/var/lib/gems/1.9.1/gems/rack-test-0.6.2/lib/rack/test.rb:57:in `get'
/var/lib/gems/1.9.1/gems/middleman-core-3.1.4/lib/middleman-core/cli/build.rb:138:in `render_to_file'
/var/lib/gems/1.9.1/gems/middleman-core-3.1.4/lib/middleman-core/cli/build.rb:280:in `block in execute!'
/var/lib/gems/1.9.1/gems/middleman-core-3.1.4/lib/middleman-core/cli/build.rb:277:in `each'
/var/lib/gems/1.9.1/gems/middleman-core-3.1.4/lib/middleman-core/cli/build.rb:277:in `execute!'
/var/lib/gems/1.9.1/gems/middleman-core-3.1.4/lib/middleman-core/cli/build.rb:199:in `invoke!'
/var/lib/gems/1.9.1/gems/thor-0.18.1/lib/thor/actions.rb:95:in `action'
/var/lib/gems/1.9.1/gems/middleman-core-3.1.4/lib/middleman-core/cli/build.rb:64:in `build'
/var/lib/gems/1.9.1/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
/var/lib/gems/1.9.1/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
/var/lib/gems/1.9.1/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
/var/lib/gems/1.9.1/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
/var/lib/gems/1.9.1/gems/middleman-core-3.1.4/lib/middleman-core/cli.rb:77:in `method_missing'
/var/lib/gems/1.9.1/gems/thor-0.18.1/lib/thor/command.rb:29:in `run'
/var/lib/gems/1.9.1/gems/thor-0.18.1/lib/thor/command.rb:128:in `run'
/var/lib/gems/1.9.1/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
/var/lib/gems/1.9.1/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
/var/lib/gems/1.9.1/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
/var/lib/gems/1.9.1/gems/middleman-core-3.1.4/lib/middleman-core/cli.rb:22:in `start'
/var/lib/gems/1.9.1/gems/middleman-core-3.1.4/bin/middleman:18:in `<top (required)>'
/usr/local/bin/middleman:23:in `load'
/usr/local/bin/middleman:23:in `<main>'
== Request: /index.html
== Finishing Request: index.html (0.0s)
   identical  build/index.html
== Request: /humans.txt
== Finishing Request: humans.txt (0.0s)
   identical  build/humans.txt
There were errors during this build
```

**Comment by axilleas** [comment]
for reference https://middlemanapp.com/basics/blogging/#draft-articles
