### ISSUE TITLE
Error with middleman 4 alpha

### ISSUE THREAD

**Issue by dwcramer** [middleman/middleman-blog#237]
Testing Middleman 4 alpha 6, I get the following error when I have `gem "middleman-blog"` in my Gemfile. Running ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]
```
/Library/Ruby/Gems/2.0.0/gems/middleman-blog-0.1.5/lib/middleman-blog/template.rb:3:in `<module:Blog>': uninitialized constant Middleman::Templates (NameError)
	from /Library/Ruby/Gems/2.0.0/gems/middleman-blog-0.1.5/lib/middleman-blog/template.rb:2:in `<module:Middleman>'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-blog-0.1.5/lib/middleman-blog/template.rb:1:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-blog-0.1.5/lib/middleman-blog.rb:2:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-blog-0.1.5/lib/middleman-blog.rb:2:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.7.0/lib/bundler/runtime.rb:76:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.7.0/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.7.0/lib/bundler/runtime.rb:72:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.7.0/lib/bundler/runtime.rb:72:in `block in require'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.7.0/lib/bundler/runtime.rb:61:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.7.0/lib/bundler/runtime.rb:61:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.7.0/lib/bundler.rb:133:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/load_paths.rb:33:in `setup_bundler'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/load_paths.rb:15:in `setup_load_paths'
	from /Library/Ruby/Gems/2.0.0/gems/middleman-cli-4.0.0.alpha.6/bin/middleman:10:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/bin/middleman:23:in `load'
	from /Library/Ruby/Gems/2.0.0/bin/middleman:23:in `<main>'
```

**Comment by dwcramer** [comment]
Nevermind, I realized I need to use the unreleased version of middleman-blog as well:
`
gem "middleman-blog", :git => 'https://github.com/middleman/middleman-blog.git'
`

**Comment by tdreyno** [comment]
Ah, yes, sorry. Not all extensions are ready for beta yet
