### ISSUE TITLE
Feed building fails in Middleman 4.0.0.alpha.6

### ISSUE THREAD

**Issue by jarkko** [middleman/middleman-blog#244]
Trying to build a site with middleman-blog 3.6.0.beta.2 fails to build the feed, with the following error:

```
       error  build/uutiset/feed.xml
no implicit conversion of Middleman::SourceFile into String
/Users/jarkko/sites/trailcup/source/uutiset/feed.xml.builder:18:in `mtime'
/Users/jarkko/sites/trailcup/source/uutiset/feed.xml.builder:18:in `block (4 levels) in singleton class'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `call'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:93:in `method_missing'
/Users/jarkko/sites/trailcup/source/uutiset/feed.xml.builder:13:in `block (3 levels) in singleton class'
/Users/jarkko/sites/trailcup/source/uutiset/feed.xml.builder:12:in `each'
/Users/jarkko/sites/trailcup/source/uutiset/feed.xml.builder:12:in `block (2 levels) in singleton class'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `call'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:93:in `method_missing'
/Users/jarkko/sites/trailcup/source/uutiset/feed.xml.builder:2:in `block in singleton class'
/Users/jarkko/sites/trailcup/source/uutiset/feed.xml.builder:-3:in `instance_eval'
/Users/jarkko/sites/trailcup/source/uutiset/feed.xml.builder:-3:in `singleton class'
/Users/jarkko/sites/trailcup/source/uutiset/feed.xml.builder:-5:in `__tilt_70098769805780'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `call'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:170:in `evaluate'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/builder.rb:20:in `evaluate'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/file_renderer.rb:79:in `block in render'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/notifications.rb:166:in `instrument'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/util.rb:116:in `instrument'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/file_renderer.rb:78:in `render'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/template_renderer.rb:92:in `_render_with_all_renderers'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/template_renderer.rb:64:in `render'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/sitemap/resource.rb:137:in `block in render'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.0/lib/active_support/notifications.rb:166:in `instrument'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/util.rb:116:in `instrument'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/sitemap/resource.rb:125:in `render'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/rack.rb:102:in `process_request'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/rack.rb:58:in `block in call'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/rack.rb:57:in `catch'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/rack.rb:57:in `call'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/urlmap.rb:66:in `block in call'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/urlmap.rb:50:in `each'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/urlmap.rb:50:in `call'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/lint.rb:49:in `_call'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/lint.rb:37:in `call'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/builder.rb:153:in `call'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/mock.rb:74:in `request'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/mock.rb:56:in `get'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/builder.rb:177:in `output_resource'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/builder.rb:109:in `each'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/builder.rb:109:in `output_files'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/builder.rb:54:in `run!'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-cli-4.0.0.alpha.6/lib/middleman-cli/build.rb:65:in `build'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:40:in `block in register'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/Users/jarkko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-cli-4.0.0.alpha.6/bin/middleman:23:in `<top (required)>'
/Users/jarkko/.rbenv/versions/2.2.0/bin/middleman:23:in `load'
/Users/jarkko/.rbenv/versions/2.2.0/bin/middleman:23:in `<main>'
```

This is because nowadays Middleman::SourceFile is a struct.

Changing the line in feed.xml.builder to 

``` ruby
xml.updated File.mtime(article.source_file.full_path).iso8601
```

should fix the issue.

**Comment by iwarner** [comment]
As this refers to Version 3 I will not be fixing this at this time.
