### ISSUE TITLE
 `<class:BlogExtension>': wrong number of arguments (2 for 1) (ArgumentError)

### ISSUE THREAD

**Issue by zackp30** [middleman/middleman-blog#247]
I have the Gemfile:

```ruby
source 'https://rubygems.org'

gem 'middleman', github: 'middleman/middleman'
gem 'middleman-blog', github: 'middleman/middleman-blog'
gem 'middleman-compass', github: 'middleman/middleman-compass'
gem 'middleman-livereload', github: 'middleman/middleman-livereload'
gem 'middleman-sprockets', github: 'middleman/middleman-sprockets'

gem 'slim'

# For faster file watcher updates on Windows:
gem 'wdm', '~> 0.1.0', :platforms => [:mswin, :mingw]

gem 'nokogiri'
gem 'sass'
gem 'neat'
gem 'bourbon'

gem 'pry'
```

To try and use Middleman v4, however, an error occurs.
````
➤➤➤ middleman  
== The Middleman is loading
/home/zack/.rvm/gems/ruby-2.1.2/bundler/gems/middleman-blog-1fd21a8f85b1/lib/middleman-blog/extension.rb:8:in `<class:BlogExtension>': wrong number of arguments (2 for 1) (ArgumentError)
        from /home/zack/.rvm/gems/ruby-2.1.2/bundler/gems/middleman-blog-1fd21a8f85b1/lib/middleman-blog/extension.rb:7:in `<module:Middleman>'
        from /home/zack/.rvm/gems/ruby-2.1.2/bundler/gems/middleman-blog-1fd21a8f85b1/lib/middleman-blog/extension.rb:6:in `<top (required)>'
        from /home/zack/.rvm/gems/ruby-2.1.2/bundler/gems/middleman-blog-1fd21a8f85b1/lib/middleman-blog.rb:14:in `require'
        from /home/zack/.rvm/gems/ruby-2.1.2/bundler/gems/middleman-blog-1fd21a8f85b1/lib/middleman-blog.rb:14:in `block in <top (required)>'
        from /home/zack/.rvm/gems/ruby-2.1.2/bundler/gems/middleman-6fef5b3a9339/middleman-core/lib/middleman-core/extensions.rb:91:in `call'
        from /home/zack/.rvm/gems/ruby-2.1.2/bundler/gems/middleman-6fef5b3a9339/middleman-core/lib/middleman-core/extensions.rb:91:in `load'
        from /home/zack/.rvm/gems/ruby-2.1.2/bundler/gems/middleman-6fef5b3a9339/middleman-core/lib/middleman-core/extension_manager.rb:37:in `activate'
        from /home/zack/news/config.rb:1:in `evaluate_configuration'
        from /home/zack/.rvm/gems/ruby-2.1.2/bundler/gems/middleman-6fef5b3a9339/middleman-core/lib/middleman-core/application.rb:273:in `instance_eval'
        from /home/zack/.rvm/gems/ruby-2.1.2/bundler/gems/middleman-6fef5b3a9339/middleman-core/lib/middleman-core/application.rb:273:in `evaluate_configuration'
        from /home/zack/.rvm/gems/ruby-2.1.2/bundler/gems/middleman-6fef5b3a9339/middleman-core/lib/middleman-core/application.rb:239:in `initialize'
        from /home/zack/.rvm/gems/ruby-2.1.2/bundler/gems/middleman-6fef5b3a9339/middleman-core/lib/middleman-core/preview_server.rb:100:in `new'
        from /home/zack/.rvm/gems/ruby-2.1.2/bundler/gems/middleman-6fef5b3a9339/middleman-core/lib/middleman-core/preview_server.rb:100:in `new_app'
        from /home/zack/.rvm/gems/ruby-2.1.2/bundler/gems/middleman-6fef5b3a9339/middleman-core/lib/middleman-core/preview_server.rb:24:in `start'
        from /home/zack/.rvm/gems/ruby-2.1.2/bundler/gems/middleman-6fef5b3a9339/middleman-cli/lib/middleman-cli/server.rb:69:in `server'
        from /home/zack/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/zack/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/zack/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
        from /home/zack/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
        from /home/zack/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
        from /home/zack/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
        from /home/zack/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
        from /home/zack/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
        from /home/zack/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor.rb:40:in `block in register'
        from /home/zack/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/zack/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/zack/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch' 
        from /home/zack/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/zack/.rvm/gems/ruby-2.1.2/bundler/gems/middleman-6fef5b3a9339/middleman-cli/bin/middleman:23:in `<top (required)>'
        from /home/zack/.rvm/gems/ruby-2.1.2/bin/middleman:23:in `load'
        from /home/zack/.rvm/gems/ruby-2.1.2/bin/middleman:23:in `<main>'
        from /home/zack/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
        from /home/zack/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'

```

Where the first line of the stacktrace is: 
```ruby
delegate :logger, to: :app 
```

Any help would be great, thanks!

**Comment by tdreyno** [comment]
Middleman blog does not yet fully support Middleman 4 (master)

**Comment by zackp30** [comment]
Ah, alright, thanks!
