### ISSUE TITLE
Middleman breaks if every article doesn't have `excerpt_ separator` characters

### ISSUE THREAD

**Issue by bobrocke** [middleman/middleman-blog#280]
If a blog `summary_separator` is set:

```
blog.summary_separator = "==="
```

and an article does not have a separator in it, Middleman throws an error:

```
TypeError: type mismatch: String given
    /Users/bob/.rvm/gems/ruby-2.3.0/gems/middleman-blog-4.0.0/lib/middleman-blog/blog_article.rb:110:in `=~'
    /Users/bob/.rvm/gems/ruby-2.3.0/gems/middleman-blog-4.0.0/lib/middleman-blog/blog_article.rb:110:in `default_summary_generator'
    /Users/bob/.rvm/gems/ruby-2.3.0/gems/middleman-blog-4.0.0/lib/middleman-blog/blog_article.rb:98:in `summary'
    /Users/bob/Dropbox/Web Development/Projects/Middleman/BRP/source/index.html.erb:11:in `block (2 levels) in singleton class'
```

All articles must have the separator.

Is that intended?

**Comment by tdreyno** [comment]
Nope, that's a bug

**Comment by iwarner** [comment]
I have tried to replicate this with the latest versions and cannot. @bobrocke If you can provide a repo then please do so. Closing for now as over 1 year old.
