### ISSUE TITLE
Internal Server Error: comparison of String with :rack failed. No helpful stack trace

### ISSUE THREAD

**Issue by stevehanson** [middleman/middleman-blog#325]
I'm just getting started with Middleman and Middleman-Blog, and I'm loving it. However, I've just run into an issue that I'm having trouble resolving.

When I try to go to a tag archive or year archive page on my site, the page just says:

> **Internal Server Error**
> comparison of String with :rack failed

When I look at my running server, there is no output. If I build with `bundle exec middleman build --verbose`, I see this stacktrace:

```
       error  build/2012/01.html
comparison of Symbol with String failed
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/tilt-2.0.5/lib/tilt/template.rb:162:in `sort!'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/tilt-2.0.5/lib/tilt/template.rb:162:in `evaluate'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/tilt-2.0.5/lib/tilt/template.rb:102:in `render'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/middleman-core-4.1.14/lib/middleman-core/file_renderer.rb:79:in `render'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/middleman-core-4.1.14/lib/middleman-core/template_renderer.rb:184:in `_render_with_all_renderers'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/middleman-core-4.1.14/lib/middleman-core/template_renderer.rb:147:in `block in render'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:166:in `instrument'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/middleman-core-4.1.14/lib/middleman-core/util.rb:21:in `instrument'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/middleman-core-4.1.14/lib/middleman-core/template_renderer.rb:146:in `render'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/middleman-core-4.1.14/lib/middleman-core/sitemap/resource.rb:154:in `render'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/middleman-core-4.1.14/lib/middleman-core/rack.rb:112:in `process_request'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/middleman-core-4.1.14/lib/middleman-core/rack.rb:66:in `block in call'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/middleman-core-4.1.14/lib/middleman-core/rack.rb:65:in `catch'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/middleman-core-4.1.14/lib/middleman-core/rack.rb:65:in `call'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/rack-2.0.1/lib/rack/urlmap.rb:68:in `block in call'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/rack-2.0.1/lib/rack/urlmap.rb:53:in `each'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/rack-2.0.1/lib/rack/urlmap.rb:53:in `call'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/middleman-autoprefixer-2.7.1/lib/middleman-autoprefixer/extension.rb:48:in `call'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/rack-2.0.1/lib/rack/head.rb:12:in `call'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/rack-2.0.1/lib/rack/lint.rb:49:in `_call'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/rack-2.0.1/lib/rack/lint.rb:37:in `call'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/rack-2.0.1/lib/rack/builder.rb:153:in `call'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/rack-2.0.1/lib/rack/mock.rb:74:in `request'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/rack-2.0.1/lib/rack/mock.rb:56:in `get'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/middleman-core-4.1.14/lib/middleman-core/builder.rb:230:in `block in output_resource'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:166:in `instrument'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/middleman-core-4.1.14/lib/middleman-core/util.rb:21:in `instrument'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/middleman-core-4.1.14/lib/middleman-core/builder.rb:223:in `output_resource'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/parallel-1.10.0/lib/parallel.rb:462:in `call_with_index'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/parallel-1.10.0/lib/parallel.rb:433:in `process_incoming_jobs'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/parallel-1.10.0/lib/parallel.rb:415:in `block in worker'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/parallel-1.10.0/lib/parallel.rb:406:in `fork'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/parallel-1.10.0/lib/parallel.rb:406:in `worker'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/parallel-1.10.0/lib/parallel.rb:397:in `block in create_workers'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/parallel-1.10.0/lib/parallel.rb:396:in `each'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/parallel-1.10.0/lib/parallel.rb:396:in `each_with_index'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/parallel-1.10.0/lib/parallel.rb:396:in `create_workers'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/parallel-1.10.0/lib/parallel.rb:338:in `work_in_processes'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/parallel-1.10.0/lib/parallel.rb:252:in `map'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/middleman-core-4.1.14/lib/middleman-core/builder.rb:135:in `output_resources'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/middleman-core-4.1.14/lib/middleman-core/builder.rb:129:in `output_files'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/middleman-core-4.1.14/lib/middleman-core/builder.rb:71:in `block in run!'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:166:in `instrument'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/middleman-core-4.1.14/lib/middleman-core/util.rb:21:in `instrument'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/middleman-core-4.1.14/lib/middleman-core/builder.rb:70:in `run!'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/middleman-cli-4.1.14/lib/middleman-cli/build.rb:80:in `block in build'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:166:in `instrument'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/middleman-core-4.1.14/lib/middleman-core/util.rb:21:in `instrument'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/middleman-cli-4.1.14/lib/middleman-cli/build.rb:79:in `build'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `block in invoke_all'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `each'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `map'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `invoke_all'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/thor-0.19.4/lib/thor/group.rb:232:in `dispatch'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:115:in `invoke'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/thor-0.19.4/lib/thor.rb:40:in `block in register'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/gems/middleman-cli-4.1.14/bin/middleman:70:in `<top (required)>'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/bin/middleman:17:in `load'
/Users/shanson/dev/gh/stevehanson/shanson/vendor/bundle/bin/middleman:17:in `<top (required)>'
/Users/shanson/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
/Users/shanson/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/shanson/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
/Users/shanson/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
/Users/shanson/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/shanson/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/shanson/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/shanson/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
/Users/shanson/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/Users/shanson/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
/Users/shanson/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
/Users/shanson/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/Users/shanson/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
/Users/shanson/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/Users/shanson/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
```

This stack trace is unfortunately not very helpful to me (a newbie with Middleman), since I don't see any reference to any of my own code. Would someone be able to help me figure out where to go from here to get my blog back up and running?

I'm on Middleman 4.1.14, Middleman Blog 4.0.1, Ruby 2.3.1, Mac OS 10.12.1.

My `config.rb` looks like this:

```ruby
page '/*.xml', layout: false
page '/*.json', layout: false
page '/*.txt', layout: false

set :markdown_engine, :redcarpet
set :markdown, :fenced_code_blocks => true, :smartypants => true

activate :autoprefixer

activate :blog do |blog|
  blog.permalink = "{title}"
  blog.layout = "post"
  blog.tag_template = "tag.html"
  blog.calendar_template = "calendar.html"
end
```

I've also tried replacing `source/tag.html.erb` and `source/calendar.html.erb` with bare-bones files:

```
---
pageable: true
per_page: 12
---
<h1>Hello</h1>
```

and I'm still getting the error. 

Thanks!

**Comment by stevehanson** [comment]
**Update**: It seems this had something to do with `redcarpet`. When I commented out the following line:

```ruby
set :markdown_engine, :redcarpet
```

I'm now able to access my tags and calendar archive pages. I kept the following line:

```ruby
set :markdown, :fenced_code_blocks => true, :smartypants => true
```

and everything seems to be working fine with Markdown, I guess using Kramdown, now. 

Is there anything special I need to do to get `redcarpet` to work with Middleman Blog? I have the gem installed and it works fine on regular posts and pages, just was causing that error on the tags and calendar pages.

**Comment by tdreyno** [comment]
Rack 1 supported Red Carpet 1 and 2. I think Rack 2 (which we moved to recently), supports only Red Carpet 2 ... but ... Middleman probably still trying to work with both and may be doing something incorrectly.

We have tests for redcarpet, but maybe not the most recent version.

Can you post your `Gemfile.lock` from when redcarpet was included?

**Comment by stevehanson** [comment]
Thanks for the reply @tdreyno. I'm using Redcarpet 3.3.4

```
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (5.0.0.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (~> 0.7)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    addressable (2.5.0)
      public_suffix (~> 2.0, >= 2.0.2)
    autoprefixer-rails (6.5.3.1)
      execjs
    backports (3.6.8)
    builder (3.2.2)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.11.1)
    compass-import-once (1.0.5)
      sass (>= 3.2, < 3.5)
    concurrent-ruby (1.0.2)
    contracts (0.13.0)
    dotenv (2.1.1)
    em-websocket (0.5.1)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.6.0)
    erubis (2.7.0)
    eventmachine (1.2.1)
    execjs (2.7.0)
    fast_blank (1.0.0)
    fastimage (2.0.1)
      addressable (~> 2)
    ffi (1.9.14)
    haml (4.0.7)
      tilt
    hamster (3.0.0)
      concurrent-ruby (~> 1.0)
    hashie (3.4.6)
    http_parser.rb (0.6.0)
    i18n (0.7.0)
    kramdown (1.13.1)
    listen (3.0.8)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    memoist (0.15.0)
    middleman (4.1.14)
      coffee-script (~> 2.2)
      compass-import-once (= 1.0.5)
      haml (>= 4.0.5)
      kramdown (~> 1.2)
      middleman-cli (= 4.1.14)
      middleman-core (= 4.1.14)
      sass (>= 3.4.0, < 4.0)
    middleman-autoprefixer (2.7.1)
      autoprefixer-rails (>= 6.5.2, < 7.0.0)
      middleman-core (>= 3.3.3)
    middleman-blog (4.0.1)
      addressable (~> 2.3)
      middleman-core (>= 4.0.0)
      tzinfo (>= 0.3.0)
    middleman-cli (4.1.14)
      thor (>= 0.17.0, < 2.0)
    middleman-core (4.1.14)
      activesupport (>= 4.2, < 5.1)
      addressable (~> 2.3)
      backports (~> 3.6)
      bundler (~> 1.1)
      contracts (~> 0.13.0)
      dotenv
      erubis
      execjs (~> 2.0)
      fast_blank
      fastimage (~> 2.0)
      hamster (~> 3.0)
      hashie (~> 3.4)
      i18n (~> 0.7.0)
      listen (~> 3.0.0)
      memoist (~> 0.14)
      padrino-helpers (~> 0.13.0)
      parallel
      rack (>= 1.4.5, < 3)
      sass (>= 3.4)
      servolux
      tilt (~> 2.0)
      uglifier (~> 3.0)
    middleman-livereload (3.4.6)
      em-websocket (~> 0.5.1)
      middleman-core (>= 3.3)
      rack-livereload (~> 0.3.15)
    middleman-sprockets (4.1.0)
      middleman-core (~> 4.0)
      sprockets (>= 3.0)
    minitest (5.10.1)
    padrino-helpers (0.13.3.3)
      i18n (~> 0.6, >= 0.6.7)
      padrino-support (= 0.13.3.3)
      tilt (>= 1.4.1, < 3)
    padrino-support (0.13.3.3)
      activesupport (>= 3.1)
    parallel (1.10.0)
    public_suffix (2.0.4)
    rack (2.0.1)
    rack-livereload (0.3.16)
      rack
    rb-fsevent (0.9.8)
    rb-inotify (0.9.7)
      ffi (>= 0.5.0)
    redcarpet (3.3.4)
    sass (3.4.22)
    servolux (0.12.0)
    sprockets (3.7.0)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    thor (0.19.4)
    thread_safe (0.3.5)
    tilt (2.0.5)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (3.0.4)
      execjs (>= 0.3.0, < 3)

PLATFORMS
  ruby

DEPENDENCIES
  builder (~> 3.0)
  middleman (~> 4.1)
  middleman-autoprefixer
  middleman-blog
  middleman-livereload
  middleman-sprockets
  redcarpet (~> 3.3, >= 3.3.3)
  tzinfo-data
  wdm (~> 0.1.0)

BUNDLED WITH
   1.13.6
```

**Comment by stevehanson** [comment]
I just downgraded to Redcarpet 2.3.0 and am also seeing the error.

**Comment by teejayvanslyke** [comment]
I'm running into this, too! You're right that dropping Redcarpet seems to fix tag pages, but now my Rouge syntax highlighting is broken. Will respond back if I find anything.

**Comment by teejayvanslyke** [comment]
So it turns out that when I remove the check for sortable symbol hashes in Tilt, this works again.

https://github.com/rtomayko/tilt/blob/master/lib/tilt/template.rb#L161-L165

Modifying the `evaluate` method to this "fixes" the problem:

```ruby
    def evaluate(scope, locals, &block)
      locals_keys = locals.keys
      locals_keys.sort!{|x, y| x.to_s <=> y.to_s}
      method = compiled_method(locals_keys)
      method.bind(scope).call(locals, &block)
    end
```

It turns out `locals` has mixed string and symbol elements and Ruby was unable to sort them, despite the Tilt codebase assuming otherwise.

Let me see if it's a problem with our Ruby version. There's a key in Tilt which determines how it'll sort the keys:

```ruby
SYMBOL_ARRAY_SORTABLE = RUBY_VERSION >= '1.9
```

**Comment by teejayvanslyke** [comment]
The commit that added that constant was made over a year ago, which makes me think perhaps it's the _inputs_ into `locals` that is the culprit. If I inspect `locals.keys`, I get this:

```ruby
["page_type", "tagname", "articles", "blog_controller", :rack, :current_path]
```

Everything but `:rack` and `:current_path` are strings.

Ha, I'm shooting in the dark on this not understanding the internals, but hopefully these details help!

**Comment by teejayvanslyke** [comment]
And ... if you want an extremely brittle yet functional short-term solution, here's a fork of tilt with those lines removed. Using it in my project now until a more reasonable solution surfaces!

https://github.com/teejayvanslyke/tilt

**Comment by iwarner** [comment]
U could also try using KramDown as a markdown engine - I have never had any issues with this.

So I am seeing that this is an issue outside of the blog / middleman remit. Please re-open if this is not the case.
