### ISSUE TITLE
Middleman server crashing when creating a fresh blog

### ISSUE THREAD

**Issue by NitishPuri** [middleman/middleman-blog#353]
## Expected behaviour
Initialize a new blog using the following commands
```
middleman init my_new_blog --template=blog
cd my_new_blog
bundle exec middleman
```
The template blog should now be served locally.

## Actual behaviour
Middleman crashes with the following trace.
```
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/tzinfo-1.2.3/lib/tzinfo/data_source.rb:182:in `rescue in create_default_data_source': No source of timezone data could be found. (TZInfo::DataSourceNotFound)
Please refer to http://tzinfo.github.io/datasourcenotfound for help resolving this error.
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/tzinfo-1.2.3/lib/tzinfo/data_source.rb:179:in `create_default_data_source'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/tzinfo-1.2.3/lib/tzinfo/data_source.rb:40:in `block in get'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/tzinfo-1.2.3/lib/tzinfo/data_source.rb:39:in `synchronize'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/tzinfo-1.2.3/lib/tzinfo/data_source.rb:39:in `get'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/tzinfo-1.2.3/lib/tzinfo/timezone.rb:661:in `data_source'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/tzinfo-1.2.3/lib/tzinfo/timezone.rb:92:in `get'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/tzinfo-1.2.3/lib/tzinfo/timezone.rb:113:in `new'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-5.0.5/lib/active_support/values/time_zone.rb:203:in `find_tzinfo'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-5.0.5/lib/active_support/values/time_zone.rb:287:in `initialize'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-5.0.5/lib/active_support/values/time_zone.rb:231:in `new'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-5.0.5/lib/active_support/values/time_zone.rb:231:in `[]'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/activesupport-5.0.5/lib/active_support/core_ext/time/zones.rb:87:in `find_zone!'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/middleman-blog-4.0.2/lib/middleman-blog/extension.rb:121:in `after_configuration'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/extension.rb:405:in `block in bind_after_configuration'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/callback_manager.rb:57:in `instance_exec'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/callback_manager.rb:57:in `block in execute'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/callback_manager.rb:57:in `execute'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/middleman-core-4.2.1/lib/middleman-core/application.rb:306:in `initialize'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/middleman-cli-4.2.1/bin/middleman:49:in `new'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/middleman-cli-4.2.1/bin/middleman:49:in `<top (required)>'
        from C:/Ruby24-x64/bin/middleman:22:in `load'
        from C:/Ruby24-x64/bin/middleman:22:in `<main>'
```

## Additional information

- Ruby version:  ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]
- Middleman version:  Middleman 4.2.1
- Middleman Blog version: 4.9
- OS version: Windows 10 Pro, x64 Build 15063

This problem is only there if i use the middleman-blog gem. Initializing a vanilla site using `middleman init` works fine.   
This issue is also there is i add this gem to a vanilla site and activate it in the `config.rb`.

**Comment by NitishPuri** [comment]
Gemfile.lock
```
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (5.0.5)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (~> 0.7)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    addressable (2.5.2)
      public_suffix (>= 2.0.2, < 4.0)
    backports (3.8.0)
    builder (3.2.3)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    compass-import-once (1.0.5)
      sass (>= 3.2, < 3.5)
    concurrent-ruby (1.0.5)
    contracts (0.13.0)
    dotenv (2.2.1)
    erubis (2.7.0)
    execjs (2.7.0)
    fast_blank (1.0.0)
    fastimage (2.1.0)
    ffi (1.9.18-x64-mingw32)
    haml (5.0.2)
      temple (>= 0.8.0)
      tilt
    hamster (3.0.0)
      concurrent-ruby (~> 1.0)
    hashie (3.5.6)
    i18n (0.7.0)
    kramdown (1.14.0)
    listen (3.0.8)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    memoist (0.16.0)
    middleman (4.2.1)
      coffee-script (~> 2.2)
      compass-import-once (= 1.0.5)
      haml (>= 4.0.5)
      kramdown (~> 1.2)
      middleman-cli (= 4.2.1)
      middleman-core (= 4.2.1)
      sass (>= 3.4.0, < 4.0)
    middleman-blog (4.0.2)
      addressable (~> 2.3)
      middleman-core (~> 4.0)
      tzinfo (>= 0.3.0)
    middleman-cli (4.2.1)
      thor (>= 0.17.0, < 2.0)
    middleman-core (4.2.1)
      activesupport (>= 4.2, < 5.1)
      addressable (~> 2.3)
      backports (~> 3.6)
      bundler (~> 1.1)
      contracts (~> 0.13.0)
      dotenv
      erubis
      execjs (~> 2.0)
      fast_blank
      fastimage (~> 2.0)
      hamster (~> 3.0)
      hashie (~> 3.4)
      i18n (~> 0.7.0)
      listen (~> 3.0.0)
      memoist (~> 0.14)
      padrino-helpers (~> 0.13.0)
      parallel
      rack (>= 1.4.5, < 3)
      sass (>= 3.4)
      servolux
      tilt (~> 2.0)
      uglifier (~> 3.0)
    minitest (5.10.3)
    padrino-helpers (0.13.3.4)
      i18n (~> 0.6, >= 0.6.7)
      padrino-support (= 0.13.3.4)
      tilt (>= 1.4.1, < 3)
    padrino-support (0.13.3.4)
      activesupport (>= 3.1)
    parallel (1.12.0)
    public_suffix (3.0.0)
    rack (2.0.3)
    rb-fsevent (0.10.2)
    rb-inotify (0.9.10)
      ffi (>= 0.5.0, < 2)
    redcarpet (3.4.0)
    sass (3.4.25)
    servolux (0.13.0)
    temple (0.8.0)
    thor (0.20.0)
    thread_safe (0.3.6)
    tilt (2.0.8)
    tzinfo (1.2.3)
      thread_safe (~> 0.1)
    uglifier (3.2.0)
      execjs (>= 0.3.0, < 3)

PLATFORMS
  x64-mingw32

DEPENDENCIES
  builder (~> 3.0)
  middleman (~> 4.1)
  middleman-blog
  redcarpet (~> 3.3, >= 3.3.3)
  tzinfo-data
  wdm (~> 0.1.0)

BUNDLED WITH
   1.15.4

```

**Comment by NitishPuri** [comment]
Closing because I abandoned middleman for pelican and would no longer be able to address any discussion on this issue.
